version: "3.9"

services:
  db:
    image: mariadb:10.5
    container_name: db_fastapi
    restart: always
    ports:
      - 3306:3306
    volumes:
     - ./volumes/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=gfridnbjkdnrjkngjkrd
      - MARIADB_USER=fastapi
      - MARIADB_USER_PASSWORD=lkgmdrkj5rd15bdgriojroi
      - MARIADB_DATABASE=FastApi
  frontend:
    build: ./images/nuxtjs
    container_name: frontend_fastapi
    restart: always
    logging:
     driver: "json-file"
     options:
      max-size: "10m"
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ../fastapi-frontend:/var/www/
  api:
    build: ./images/python-fastapi
    container_name: api_fastapi
    restart: always
    logging:
     driver: "json-file"
     options:
      max-size: "10m"
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ../fastapi:/home/fastapi
    environment:
      - DATABASE_URL=mysql://root:gfridnbjkdnrjkngjkrd@db:3306/FastApi
